## Numpy Array and Basics 

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1 , 2,3 , 4,5])
print(arr_1d)

[1 2 3 4 5]


In [4]:
arr_2d = np.array([[1, 2,3],[4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]


### List vs Numpy


In [5]:
py_list = [1 ,2, 3]
print("Python List Multiply" , py_list * 2)

Python List Multiply [1, 2, 3, 1, 2, 3]


In [6]:
np_arr = np.array([2, 4, 5])
print(np_arr*2)

[ 4  8 10]


In [9]:
import time
start = time.time()
py_list = [i * 2  for i in range(1000000)]
print("\n List Operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation time: ",time.time() - start)


 List Operation time:  0.12537097930908203

 Numpy Operation time:  0.008006095886230469


### Creating array from Scratch


In [19]:
zeroes = np.zeros((3 , 4))
print("Full zeroes \n",zeroes)

ones = np.ones((4 , 5))
print("Ones Zeroes \n",ones)

full = np.full((2 , 2) , 7)
print("Full array \n",full)

random = np.random.random((2 , 3))
print("Random array \n" , random)
sequence  = np.arange(0 , 11, 2)
print("Sequence array \n" , sequence)

Full zeroes 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Zeroes 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full array 
 [[7 7]
 [7 7]]
Random array 
 [[0.44656085 0.92489068 0.34083113]
 [0.875223   0.68398431 0.44052897]]
Sequence array 
 [ 0  2  4  6  8 10]


### Vector , Matrix and Tensor 

In [23]:
vector = np.array([1 ,2 ,4,5])
print("Vector \n" , vector)

matrix = np.array([[1 , 2, 3] , [4 , 5,6]])
print("Matrix \n" , matrix)

tensor = np.array([[[1 , 2] , [3 , 4]] 
                   ,[[5 , 6] ,[7 , 8]]])
print("Tensor \n" , tensor)

Vector 
 [1 2 4 5]
Matrix 
 [[1 2 3]
 [4 5 6]]
Tensor 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties 


In [25]:
arr = np.array([[1 ,2 ,3] ,[4 , 5, True]])
print("Shape " , arr.shape)
print("Dimension ", arr.ndim)
print("Size" , arr.size)
print("DType" , arr.dtype)


Shape  (2, 3)
Dimension  2
Size 6
DType int64


### Array Reshaping 


In [31]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3 , 4))
print("Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("Flattened \n", flattened)

# ravel --> returns view , instead of copy
raveled = reshaped.ravel()
print("\n Raveled ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transposed Array" , transpose)
print()

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

