## Numpy Array Operations

In [1]:
import numpy as np


In [5]:
arr = np.array([1 , 2, 3 , 4, 5 , 6 , 7 , 8, 9,10])
print("Basics Slicing ", arr[2:7])
print("With Step" , arr[1:8:2])
print("Negative indexing " ,arr[-3])


Basics Slicing  [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing  8


In [ ]:
arr_2d = np.array([[1 ,2, 3],[4 , 5, 6] ,[7, 8 ,9]])
print("Specific Element ", arr_2d[1 , 2])
print("Entire row",arr_2d[1])
print("Entire row ",arr_2d[:,1])

Specific Element  6
Entire row [4 5 6]
Entire row  [2 5 8]


## Sorting


In [ ]:
unsorted = np.array([1 , 4 , 99 , 23 , 12 ,77])
print("Sorted Array" , np.sort(unsorted))

arr_2d_unsorted = np.array([[3 , 1] ,[1 , 2] , [2 , 3]])
print("Sorted 2d Array by column ", np.sort(arr_2d_unsorted , axis = 0))
# column - axix = 0 , row - axis = 1

Sorted Array [ 1  4 12 23 77 99]
Sorted 2d Array by column  [[1 1]
 [2 2]
 [3 3]]


## Filter


In [15]:
numbers = np.array([1 , 2 ,3 , 4 , 5 , 6 ,7 , 8, 9 , 10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers " , even_number)

Even Numbers  [ 2  4  6  8 10]


## Filter with Mask


In [17]:
mask = numbers > 5
print("Mask" , mask)
print("Numbers greater than 5 " , numbers[mask])

Mask [False False False False False  True  True  True  True  True]
Numbers greater than 5  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [23]:
indices = [0 , 2 , 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where" , numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [27]:
conditon_array = np.where(numbers > 5 , numbers *2 , numbers)
print(conditon_array)


[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [29]:
arr1 = np.array([12 , 4 , 5,9])
arr2 = np.array([3 , 8 , 11 , 10])
addition = arr1 + arr2
print("Additon " , addition)

combined = np.concatenate((arr1 , arr2))
print("Combined  ", combined)

Additon  [15 12 16 19]
Combined   [12  4  5  9  3  8 11 10]


### Array Compatibility

In [35]:
a = np.array([1 ,2 , 3])
b = np.array([4 , 5 ,6])
c = np.array([7, 8 , 9])

print("Compatability ",a.shape  == b.shape)


Compatability  True


In [41]:
original = np.array([[1 , 2] , [3 , 4]])
new_row = np.array([[5 , 6]])
with_new_row = np.vstack((original , new_row))
print(original)
print(with_new_row)

new_col = np.array([[7 ], [8]])
with_new_col = np.hstack((original , new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1 , 2 ,3 , 4, 5])
deleted = np.delete(arr , 2)
print("Array after deletion ",deleted)

[1 2 4 5]
